%data=load('C:\Users\asus\Desktop\shujuchuli\data_Tohoku2011-2020\data_Tohoku2011-2020\obsdata\CHOS\CHOS.1204.meiyo_m4-svp.csv');
filename='C:\Users\asus\Desktop\shujuchuli\data_Tohoku2011-2020\data_Tohoku2011-2020\obsdata\CHOS\CHOS.2006.meiyo_m5-svp.csv';
a=csvread(filename,2);
x=a(:,2);
x2=a(:,1);
y=-1*x2;
%x3=data(:,3);
plot(x,y,'-','Color','b',...
                'MarkerEdgeColor','m',...
               'MarkerFaceColor','m',...
                'MarkerSize',5);
xlabel('Sound speed(m/s)');
ylabel('Depth(m)');
  %x3=linspace(2011,2020,30);               
%plot(x1,x2,'d-','Color','r',...
              % 'MarkerEdgeColor','k',...
             % 'MarkerFaceColor','g',...
             %  'MarkerSize',5);
     %plot(data,'-','LineWidth',1,'Color','b',...
             %  'MarkerEdgeColor','m',...
             %  'MarkerFaceColor','m',...
             %  'MarkerSize',3); 
 %% »æÍ¼
%Par.PlotFun(Data,Par)
%FigPrintSetting(Par.FigSet,H);
%plot(Data);